### ISSUE TITLE
Setup local development environment on MacOS

### ISSUE THREAD

**Issue by lagatanegra** [tablexi/nucore-open#2408]
Hi , i would like to setup a local development of NuCore environment on MacOS .
I followed the section "Development Locally" at Readme, but the "bundle install" command returns error when trying to install gem kostya-sigar (2.0.6). 
Attached the errors during installation. 
[gem_make.out.txt](https://github.com/tablexi/nucore-open/files/5250006/gem_make.out.txt)
My OS version: Mac 10.15.6
I used rbenv to install: ruby 2.5.5, bundler version is 2.1.4

Please kindly advise. Thanks!

**Comment by jhanggi** [comment]
I recently ran into this issue on another project, but haven't found a solution yet. I suspect something in one of the newer macOS versions is causing it. 

The `kostya-sigar` gem is a dependency of `eye`/`eye-patch` which is a process manager we use for running the app in staging/production. In the short term, you should be able to remove/comment out the line `gem "eye-patch", require: false` in `Gemfile` and re-run `bundle install`.

Hopefully, we'll have a solution for this issue before you need to deploy the application.

**Comment by lagatanegra** [comment]
@jhanggi  Thanks a lot. I will comment out the dependency and try again.

**Comment by giladshanan** [comment]
@lagatanegra it looks like this `kostya-sigar` [issue](https://github.com/kostya/sigar/pull/9) has been fixed in version [2.0.8](https://github.com/kostya/sigar#208-02-10-2020).  We upgraded in https://github.com/tablexi/nucore-open/pull/2479 so I'm going to close this now.
